# Basisconfiguratie voor de website

baseURL = "https://www3.nluug.nl/"
languageCode = "nl"
defaultContentLanguage = "nl"
title = "NLUUG"
theme = "nluug"
enableGitInfo = true
disableHugoGeneratorInject = true

# EOF
