# Menu-configuratie

  [[main]]
    identifier = "organisatie"
    name = "Organisatie"
    url = "/organisatie/"
    weight = 10

  [[main]]
    identifier = "organisatie-doelstellingen"
    name = "Doelstellingen"
    url = "/organisatie/doelstellingen/"
    parent = "organisatie"
    weight = 11

  [[main]]
    identifier = "organisatie-bestuur"
    name = "Bestuur"
    url = "/organisatie/bestuur/"
    parent = "organisatie"
    weight = 12

  [[main]]
    identifier = "organisatie-commissies"
    name = "Commissies"
    url = "/organisatie/commissies/"
    parent = "organisatie"
    weight = 13

  [[main]]
    identifier = "evenementen"
    name = "Evenementen"
    url = "/evenementen/"
    weight = 20

  [[main]]
    identifier = "evenementen-kalender"
    name = "Kalender"
    url = "/evenementen/kalender/"
    parent = "evenementen"
    weight = 21

  [[main]]
    identifier = "lidmaatschap"
    name = "Lidmaatschap"
    url = "/lidmaatschap/"
    weight = 30

  [[main]]
    identifier = "lidmaatschap-tarieven"
    name = "Tarieven"
    url = "/lidmaatschap/tarieven/"
    parent = "lidmaatschap"
    weight = 31

  [[main]]
    identifier = "lidmaatschap-aanmelden"
    name = "Aanmelden"
    url = "/lidmaatschap/aanmelden/"
    parent = "lidmaatschap"
    weight = 32

  [[main]]
    identifier = "nieuws"
    name = "Nieuws"
    url = "/nieuws/"
    weight = 40

  [[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50

[[footer]]
  name = 'Terms'
  pageRef = '/terms'
  weight = 10
[[footer]]
  name = 'Privacy'
  pageRef = '/privacy'
  weight = 20

# EOF
