# Configuratie tbv exporteerde formaten

# RSS-feed (Atom)
[RSS]
  mediatype = "application/xml"
  baseName = "atom"

# JSON Feed: feed.json
[JSON]
  mediatype = "application/json"
  baseName = "feed"

# IndexNow-bestand: indexnow.json
[IndexNow]
  mediatype = "application/json"
  baseName = "indexnow"

# CalendarEvent genereerd een iCal-bestand voor evenementen
[CalendarEvent]
  mediaType = "text/calendar"
  baseName = "calendar"

# Index voor zoekfunctionaliteit op de website
[SearchIndex]
  mediatype = "application/json"
  basename = "searchindex"

#[outputFormats.XMLEvent]
#  mediaType = "application/xml"
#  baseName = "schedule"

# EOF
