# Aanvullende velden die we binnen de website gebruiken

[params]
  description = "NLUUG website met de doelstellingen, laatste nieuws en evenementen van onze vereniging."
  # Fallback-auteur voor posts die geen echte auteur hebben
  author = "NLUUG"
  # Datum-formaat en tijdzone, de gebruikte waardes in datum en tijd zijn van belang
  dateFormat = "02-01-2006"
  timeZone = "Europe/Amsterdam"
  # Grafisch
  logo = "/assets/favicon.ico"

# EOF
