baseURL = 'https://www3.nluug.nl/'
languageCode = 'nl'
title = 'NLUUG'
theme = 'nluug'

languagecode = "nl"
defaultcontentlanguage = "nl"


[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "NLUUG website met de doelstellingen, laatste nieuws en evenementen van onze vereniging."
  # Fallback-auteur voor posts die geen echte auteur hebben
  author = 'NLUUG'
  # Datum-formaat en tijdzone
  dateFormat = "02-01-2006"
  timeZone = "Europe/Amsterdam"

[menu]
  [[menu.main]]
    identifier = "organisatie"
    name = "Organisatie"
    url = "/organisatie/"
    weight = 10
  [[menu.main]]
    identifier = "evenementen"
    name = "Evenementen"
    url = "/evenementen/"
    weight = 20
  [[menu.main]]
    identifier = "lidmaatschap"
    name = "Lidmaatschap"
    url = "/lidmaatschap/"
    weight = 30
  [[menu.main]]
    identifier = "nieuws"
    name = "Nieuws"
    url = "/nieuws/"
    weight = 40
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]
  page = ["HTML", "CalendarEvent"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[outputFormats.CalendarEvent]
  mediaType = "text/calendar"
  baseName = "calendar"

#[outputFormats.XMLEvent]
#  mediaType = "application/xml"
#  baseName = "schedule"


#ignoreErrors = ["error-remote-getjson"]

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^rst2html$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|GIT_EXEC_PATH|LD_LIBRARY_PATH|npm_config_(cache|init_module|userconfig)|pandoc_datadir|PYTHONHOME|RUBYLIB|SNAP)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']


# EOF
