# Menu-configuratie

[menu]
  [[menu.main]]
    identifier = "organisatie"
    name = "Organisatie"
    url = "/organisatie/"
    weight = 10
  [[menu.main]]
    identifier = "evenementen"
    name = "Evenementen"
    url = "/evenementen/"
    weight = 20
  [[menu.main]]
    identifier = "evenementen-kalender"
    name = "Kalender"
    url = "/evenementen/kalender/"
    parent = "evenementen"
    weight = 21
  [[menu.main]]
    identifier = "lidmaatschap"
    name = "Lidmaatschap"
    url = "/lidmaatschap/"
    weight = 30
  [[menu.main]]
    identifier = "nieuws"
    name = "Nieuws"
    url = "/nieuws/"
    weight = 40
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50

# EOF
