# Configuratie tbv exporteerde formaten

# Voor de home-page maken we een HTML, RSS en JSON Feed
# Secties alleen in HTML en voor pagina's in zowel HTML als CalendarEvent (iCAL) waar het van toepassing is
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]
  page = ["HTML", "CalendarEvent"]

# RSS-feed (Atom)
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

# JSON Feed, index.json
[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

# CalendarEvent genereerd een iCal-bestand voor evenementen
[outputFormats.CalendarEvent]
  mediaType = "text/calendar"
  baseName = "calendar"

#[outputFormats.XMLEvent]
#  mediaType = "application/xml"
#  baseName = "schedule"

# EOF
