# Menu-configuratie

  [[main]]
    identifier = "organization"
    name = "Organisatie"
    pageRef = "/organisatie"
    weight = 10

  [[main]]
    identifier = "organization-goals"
    name = "Doelstellingen"
    url = "/organisatie/doelstellingen/"
    parent = "organization"
    weight = 11

  [[main]]
    identifier = "organization-board"
    name = "Bestuur"
    url = "/organisatie/bestuur/"
    parent = "organization"
    weight = 12

  [[main]]
    identifier = "organization-committees"
    name = "Commissies"
    url = "/organisatie/commissies/"
    parent = "organization"
    weight = 13

  [[main]]
    identifier = "nluug-award"
    name = "NLUUG Award"
    url = "/organisatie/nluug-award/"
    parent = "organization"
    weight = 14

  [[main]]
    identifier = "events"
    name = "Evenementen"
    url = "/evenementen/"
    weight = 20

  [[main]]
    identifier = "events-calendar"
    name = "Kalender"
    url = "/evenementen/kalender/"
    parent = "events"
    weight = 21

  [[main]]
    identifier = "membership"
    name = "Lidmaatschap"
    url = "/lidmaatschap/"
    weight = 30

  [[main]]
    identifier = "lidmaatschap-tarieven"
    name = "Tarieven"
    url = "/lidmaatschap/tarieven/"
    parent = "membership"
    weight = 31

  [[main]]
    identifier = "lidmaatschap-aanmelden"
    name = "Aanmelden"
    url = "/lidmaatschap/aanmelden/"
    parent = "membership"
    weight = 32

  [[main]]
    identifier = "lidmaatschap-ereleden"
    name = "Ereleden"
    url = "/lidmaatschap/ereleden/"
    parent = "membership"
    weight = 33

  [[main]]
    identifier = "news"
    name = "Nieuws"
    url = "/nieuws/"
    weight = 40

  [[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50

  [[footer]]
    identifier = "terms"
    name = "Algemene Voorwaarden"
    pageRef = "/algemene-voorwaarden/"
    weight = 10

  [[footer]]
    identifier = "privacy"
    name = "Privacy"
    pageRef = "/privacy/"
    weight = 20

# EOF
